<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>Patware.Pipeline.Runtime</PackageId>
    <Version>0.1.0</Version>
    <Authors>Patware</Authors>
    <Description>The runtime for the composable pipeline library for .NET.</Description>
    <PackageTags>pipeline;dotnet</PackageTags>
    <RepositoryUrl>https://github.com/patware/Patware.Pipeline</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <None Update="README.md" Pack="true" PackagePath="/" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Pipeline.Core\Pipeline.Core.csproj" />
  </ItemGroup>

</Project>
